# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13e07303a24800a80a52f5ee4f2ee42d14e198d2157b130dc542bdf4c4cfb4c3fe812d64ac1f0e6c66d95da7a359bcb167a703f5463a0db6430bf8b970c57ebd

test:
  secret_key_base: 9c08d623b525c5fe093a7b801fa15b7a9c41cfb71b4502f9b2851757fbc2354da24c6c8656e9d433965db355d13786a16af32189ba2382beef004d24426ef9cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
